- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
  - name: Add repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  - name: Update rep
    apt:
      update_cache: yes
  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present
  - name: Run mongo
    systemd:
      name: mongod
      enabled: yes

