---
dependency:
  name: galaxy
driver:
  name: vagrant
  no_log: false 
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    no_log: false 
    box: ubuntu/xenial64
provisioner:
  name: ansible
  no_log: false 
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
